#include<iostream>
/* Preprocessor directives are lines included in the code of programs
preceded by a hash sign (#). These lines are not program statements but directives for the
preprocessor. The preprocessor examines the code before actual compilation of code begins
 and resolves all these directives before any code is actually generated by regular statements.

These preprocessor directives extend only across a single line of code. As soon as a newline
character is found, the preprocessor directive is ends. No semicolon (;) is expected at the
end of a preprocessor directive. The only way a preprocessor directive can extend through more
 than one line is by preceding the newline character at the end of the line by a backslash (\).*/


using namespace std;
/*Namespaces allow us to group named entities that otherwise would have global scope into narrower
 * scopes, giving them namespace scope. This allows organizing the elements of programs into
 * different logical scopes referred to by names.*/

/*The main function is called at program startup after initialization of the non-local
 * objects with static storage duration. It is the designated entry point to a program
 * that is executed in hosted environment */
// int is the return type of the main function
int main3(){
	// cout puts values to the console
	cout<<"Hello World!\n";
	// return returns value when function execution is complete
	return 0;

}
// for more info goto http://www.cplusplus.com/
